### PR TITLE
Allow users to enable/disable ncsos globally

### PR DESCRIPTION
**Pull request by lesserwhirls**
Bring ncSOS into line with other TDS services by allowing users to enable/disable the service globally within threddsConfig.xml

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Fixes asascience-open/ncsos#186

The section of threddsConfig.xml looks like:

~~~xml
<NCSOS>
  <allow>false</allow>
</NCSOS>
~~~

The default is to disable the service, as this is a new service. However, in TDS v5.0, the default should be changed to true, as this will allow the use of ncSOS as a `StandardService`, which basically means it will be enabled and exposed by default on `PointFeature Collections` without the need for users to explicitly add the service in the configuration catalog.

**Comment by cheryldmorse** [comment]
Nice. Thanks @lesserwhirls

**Comment by lesserwhirls** [comment]
Great - thank you! Any idea when this will get into an artifact on your maven server? We are planning a release for next week, and it would be awesome to get this in for it (even if we reference a snapshot artifact). However, if that's too soon, I totally understand. We can pick it up on the next release. Thank you @cheryldmorse!

**Comment by cheryldmorse** [comment]
Hi @lesserwhirls,  Version 1.4.3 is now on the maven server.

**Comment by lesserwhirls** [comment]
Awesome, thank you @cheryldmorse!

**Pull request merged**
